/*****************************************************************************************************
* Created By    :     Nanthavarman Lingeswaran
* Create Date   :     13/01/2023
* Description   :     Constant class for NEO
*    -----------------------------------------------------------------------------
*    * Developer                          Date               Description
*    * ----------------------------------------------------------------------------
*    * Nanthavarman Lingeswaran           13/01/2023         Created
******************************************************************************************************/
public with sharing class NEO_Constants {
    public static final String PRODUCT_FAM_MONTHLY_SUBS = 'Monthly Subscription';
    public static final String PRODUCT_FAM_ATM = 'ATM';
    public static final String PRODUCT_FAM_CARD_REPLACE = 'Card Replacement';
}